In [1]:
#list的運算,需要利用迴圈
import random
chinese = [random.randint(60, 100) for _ in range(50)]
english = [random.randint(60, 100) for _ in range(50)]

result = []
for i in range(50):
    total = chinese[i] + english[i]
    result.append(total)

result

[165,
 192,
 156,
 182,
 162,
 146,
 154,
 158,
 169,
 132,
 170,
 143,
 173,
 185,
 188,
 155,
 158,
 157,
 146,
 181,
 164,
 189,
 144,
 180,
 131,
 151,
 192,
 127,
 154,
 168,
 194,
 163,
 158,
 143,
 179,
 168,
 177,
 140,
 136,
 140,
 154,
 169,
 161,
 161,
 173,
 133,
 136,
 172,
 184,
 156]

In [3]:
#使用numpy,陣列運算

import numpy as np
chinese = np.random.randint(60, high=100, size=50)
english = np.random.randint(60, high=100, size=50)
result = chinese + english
result

array([133, 151, 175, 166, 135, 192, 159, 157, 172, 152, 141, 191, 180,
       175, 150, 142, 141, 124, 144, 139, 155, 162, 143, 161, 176, 160,
       159, 162, 177, 162, 192, 164, 128, 172, 154, 145, 164, 187, 167,
       184, 136, 165, 134, 183, 189, 157, 139, 152, 168, 160])

In [4]:
#50個學生,5個分數
import numpy as np

students = np.random.randint(60,high=100,size=(50, 5)) #2維
print(students)
sum = np.sum(students,axis=1)
average = np.average(students,axis=1)
print(sum)
print("============")
print(average)

[[89 75 95 60 66]
 [80 62 84 71 81]
 [61 79 70 71 67]
 [84 94 70 76 64]
 [87 88 61 76 65]
 [95 83 99 96 70]
 [92 85 76 97 71]
 [66 91 87 60 60]
 [81 71 76 97 79]
 [74 88 97 74 94]
 [63 64 80 70 90]
 [63 78 84 62 80]
 [67 96 82 65 62]
 [98 73 65 78 97]
 [96 62 61 84 88]
 [74 70 64 96 89]
 [75 65 62 86 63]
 [60 91 98 80 61]
 [85 66 64 79 67]
 [96 62 81 86 80]
 [81 75 76 69 92]
 [73 69 72 74 94]
 [72 92 97 75 85]
 [78 83 87 98 71]
 [62 70 81 72 61]
 [66 96 74 90 93]
 [95 75 95 92 61]
 [73 66 74 81 60]
 [61 64 65 75 72]
 [95 77 72 82 86]
 [66 91 88 80 94]
 [91 84 97 92 86]
 [72 83 96 73 60]
 [69 97 61 81 92]
 [86 87 79 97 74]
 [66 62 74 63 95]
 [80 89 63 94 93]
 [83 68 88 86 60]
 [93 69 95 69 83]
 [96 99 91 71 74]
 [65 90 66 79 68]
 [99 61 60 69 76]
 [64 82 78 61 89]
 [78 66 75 94 84]
 [93 92 61 76 85]
 [75 88 70 99 75]
 [78 69 92 65 67]
 [88 63 69 75 83]
 [72 75 76 90 79]
 [68 67 62 70 71]]
[385 378 348 388 377 443 421 364 404 427 367 367 372 411 391 393 351 390
 361 405 393 382 421 417 3

In [5]:
for i in range(50):
    print(students[i])

[89 75 95 60 66]
[80 62 84 71 81]
[61 79 70 71 67]
[84 94 70 76 64]
[87 88 61 76 65]
[95 83 99 96 70]
[92 85 76 97 71]
[66 91 87 60 60]
[81 71 76 97 79]
[74 88 97 74 94]
[63 64 80 70 90]
[63 78 84 62 80]
[67 96 82 65 62]
[98 73 65 78 97]
[96 62 61 84 88]
[74 70 64 96 89]
[75 65 62 86 63]
[60 91 98 80 61]
[85 66 64 79 67]
[96 62 81 86 80]
[81 75 76 69 92]
[73 69 72 74 94]
[72 92 97 75 85]
[78 83 87 98 71]
[62 70 81 72 61]
[66 96 74 90 93]
[95 75 95 92 61]
[73 66 74 81 60]
[61 64 65 75 72]
[95 77 72 82 86]
[66 91 88 80 94]
[91 84 97 92 86]
[72 83 96 73 60]
[69 97 61 81 92]
[86 87 79 97 74]
[66 62 74 63 95]
[80 89 63 94 93]
[83 68 88 86 60]
[93 69 95 69 83]
[96 99 91 71 74]
[65 90 66 79 68]
[99 61 60 69 76]
[64 82 78 61 89]
[78 66 75 94 84]
[93 92 61 76 85]
[75 88 70 99 75]
[78 69 92 65 67]
[88 63 69 75 83]
[72 75 76 90 79]
[68 67 62 70 71]
